### ISSUE TITLE
Ignoring bone in children

### ISSUE THREAD

**Issue by yanagiragi** [ichika292/MMD4MecanimJitter#1]
Great Works! However there's a suggestion:

How about making optional parameters for ignoring bone in children?

I think in some conditions it may be needed, such as I've tried to simulation shoulder raises when breathing, however if I apply BoneJitter on Torse every bone under hierarchy will be effected.

Anyway, Really Nice Works! Thanks A Lot!

**Comment by ichika292** [comment]
(Google Translate)
Thank You For Using!
First of all, because I am not good at English, your intention may not be accurately grasped.

Do you mean that you want to move Torso for reproduction of breath, do not want to move the position of the hands or the head?
MMD4MecanimBone.userRotation (Script Execution Order: 20,000~ Override rotation) is Forward Kinematics. (not IK)
In other words, I think that it is not very suitable for this type of problem.

It is a difficult problem for me, so I will try to think about solutions, but please do not expect too much.
However, I intended to make this that can be used for general purpose (At the distal bone) so please try various things! Thank You!

**Comment by yanagiragi** [comment]
Yes, that's exactly what I mean!
It seems like doing this may need to trace whole MMD4Mecanim for searching IK parts (Not really sure how to even use it, I've tried using it on but no effects :( )

For current, I thought it may not be a big issue, so I still use BoneJitter with less aptitude so that my arms won't effect so much but the model still acts like human.

Please feel no pressure about this request, it's just a suggestion(and a chance to thank you for your works)! Really appreciated for what you've done. 

Thanks a lot.

**Comment by ichika292** [comment]
I also think that this is suitable for expressing small fluctuations, too.
Thank you for taking the trouble to tell. I'm very happy and encouraged! :)
